/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIYASA;

import javax.swing.JOptionPane; //kegunaan joption pane mengimport semua fungsi dari joption pain untuk mengeluarkan pop up
import javax.swing.table.DefaultTableModel; //untuk mengimport semua fungsi dari tabel
import java.sql.Connection; //unutk mengimport semua fungsi connection
import java.sql.ResultSet; //untuk mengimport semua fungsi result set
import java.sql.Statement; //untuk mengimport semua fungsi statement
import java.sql.*; //untuk mengimport semua objek yang ada didalam sql



/**
 *
 * @author Yasa Kamil
 */
public class HotelReservationRegistration extends javax.swing.JFrame { //untuk menampung semua codingan //extends berguna untuk mengimplementasikan fungsi jframe kepada class ini
    ResultSet rst=null ; //
    Connection conn=null;
    PreparedStatement pst=null;
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
//    Connection cn = koneksi.Koneksi.Koneksi();
    
     public void judul() {
  Object[] judul = {
    "Customer Code", "Name", "Phone Number", "Email", "Room Number"
  };
  tabModel = new DefaultTableModel(null, judul);
  tblRegistration.setModel(tabModel);
}
     
     
     
     private void tampilkan_data(){
        String perintah = "SELECT * FROM customer_table";

        try {
            pst = conn.prepareStatement(perintah);
            rst = pst.executeQuery();
            DefaultTableModel admin = new DefaultTableModel();
            admin.addColumn("Customer Code");
            admin.addColumn("Name");
            admin.addColumn("Phone Number");
            admin.addColumn("Email");
            admin.addColumn("Room Number");
            

           
            while (rst.next()){
                admin.addRow(new Object[]{
                    rst.getString(1),
                    rst.getString(2),
                    rst.getString(3),
                    rst.getString(4),
                    rst.getString(5)
                });

            }
            tblRegistration.setModel(admin);

        } catch (SQLException ex) {
            System.out.println(ex);
        }

 }
     
     
     
     
     //=======tampilData=========================
   
//public void tampilData(String where) {
//  try {
//    st = cn.createStatement();
//    tabModel.getDataVector().removeAllElements();
//    tabModel.fireTableDataChanged();
//    rs = st.executeQuery("select * from customer_table" + where);
//    
//    while (rs.next()) {
//      Object[] data = {
//        rs.getString("custcode"),
//        rs.getString("name"),
//        rs.getString("phonenum"),
//        rs.getString("email"),
//        rs.getString("roomnum"),
//      };
//        
//        tabModel.addRow(data);
//    }
//  } catch(Exception e) {
//    e.printStackTrace();
//  }
//}
 
     
    /**
     * Creates new form HotelReservationRegistration
     */
     
    public HotelReservationRegistration() {
        initComponents();
//        judul();
//        tampilData("");

try {
            conn = koneksi.Koneksi.Koneksi();
             tampilkan_data();

        } catch (SQLException ex) {
            System.out.println("form tidak dapat terhubung ke DB");
        }

        
  
  //btnDelete.setEnabled(false);
  //btnUpdate.setEnabled(false);
    }
    public HotelReservationRegistration(String msg) {
        initComponents();
        txtRoom.setText(msg);
    }
    
   



    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistration = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtRoom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCustomercode = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel1.setText("NUSANTARA REGISTRATION");

        jLabel2.setText("Name              :");

        jLabel3.setText("Phone Number :");

        jLabel4.setText("Email              :");

        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        jButton1.setText("Input");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back to Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblRegistration.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Code", "Name", "Phone Number", "Email", "Room Number"
            }
        ));
        tblRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistrationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistration);

        jLabel5.setText("Room             :");

        txtRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomActionPerformed(evt);
            }
        });

        jLabel6.setText("Customer Code:");

        jButton3.setText("Generate Code");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(183, 183, 183))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addComponent(txtPhoneNumber)
                            .addComponent(txtRoom)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCustomercode))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCustomercode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(btnDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btnUpdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    new HotelReservationMainMenu().show();
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String perintah ="INSERT INTO customer_table(custcode,name,phonenum,email,roomnum) VALUE (?,?,?,?,?)";


        try {
             pst=conn.prepareStatement(perintah);
             pst.setString(1 ,txtCustomercode.getText());
             pst.setString(2 ,txtName.getText());
             pst.setString(3 ,txtPhoneNumber.getText());
             pst.setString(4,txtEmail.getText());
             pst.setString(5,txtRoom.getText());



             pst.execute();
             JOptionPane.showMessageDialog(null, "Data Berhasil di Input");
             tampilkan_data();
          


         } 

    catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, ex);

             //Logger.getLogger(Daftar_Sparepart.class.getName()).log(Level.SEVERE, null, ex);
         }
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     if (txtName.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Type the name of the reserver before generating the reservation code");
    txtName.requestFocus();
    }
    else {
    java.util.Random r = new java.util.Random();
    int start = 10000;
    int end = 100000;
    int result = r.nextInt(end-start) + start;
    txtCustomercode.setText(String.valueOf(result));
     }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    
        int row = tblRegistration.getSelectedRow(); 
        String diklik = (tblRegistration.getModel().getValueAt(row, 0).toString()); 
        String perintah_hapus = "DELETE FROM customer_table WHERE custcode=?"; 

         try {

             pst= conn.prepareStatement(perintah_hapus); 
             pst.setString(1,diklik); 
             pst.execute(); 
             JOptionPane.showMessageDialog(null, "Data berhasil dihapus"); 
            tampilkan_data(); 
             

         } 

         catch (SQLException ex) { 
            // Logger.getLogger(Daftar_Sparepart.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
         }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistrationMouseClicked
        int row =tblRegistration.getSelectedRow();   
        String diklik=(tblRegistration.getModel().getValueAt(row,0).toString());
        String perintah ="SELECT * from customer_table where custcode='"+diklik+"'";

         try {
             pst = conn.prepareStatement(perintah);
             rst = pst.executeQuery();
             
             if(rst.next()){
                 
                 
                 
                String tulisan1= rst.getString("custcode");
                txtCustomercode.setText(tulisan1);
                
                String tulisan2= rst.getString("name");
                txtName.setText(tulisan2);
                
                String tulisan3= rst.getString("phonenum");
                txtPhoneNumber.setText(tulisan3);
                
                String tulisan4= rst.getString("email");
                txtEmail.setText(tulisan4);
                
                String tulisan5= rst.getString("roomnum");
                txtRoom.setText(tulisan5);
                
               
             }
             
         } catch (SQLException ex) {
             System.out.println(ex);
         } 
        
    }//GEN-LAST:event_tblRegistrationMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    int row =tblRegistration.getSelectedRow();
        String diklik=(tblRegistration.getModel().getValueAt(row,0).toString());
            String perintah ="UPDATE customer_table SET name= ?,phonenum=?,email=?,roomnum=? where custcode=?";

         try {
             pst = conn.prepareStatement(perintah);
             
             pst.setString(1,txtName.getText());
             pst.setString(2,txtPhoneNumber.getText());
             pst.setString(3,txtEmail.getText());
             pst.setString(4,txtRoom.getText());
             pst.setString(5, diklik);

             pst.execute();
             tampilkan_data();



             JOptionPane.showMessageDialog(null,"Data Berhasil Di Input");
           
         } catch (SQLException ex) {

         }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelReservationRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelReservationRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelReservationRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelReservationRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelReservationRegistration().setVisible(true);
            }
        });
    }

     //jadi kita menggunakan button delete di project kali ini dan akan menjelaskan secara singkat
    //untuk mendekralasi varibel row memiliki fungsi yaitu get selected row dari table registration 
    //untuk mendekralasikan bahwa variable diklik akan mengambil data pada row yang telah diselect dan mengubahnya menjadi string
    //kenapa string perintah hapus untuk menanampung querry nya
    //prepare statemen disini digunakan untuk memanipulasi querry yang mempunyai parameter
    //set string pada project kita kali ini untuk ngeset value pada suatu string
    //untuk mengeksekusi queery tersebut
    //menampilan pop up jika berhasil
    //berguna untuk menampilan datanya kembali
    //menangkap kesalahn yang terjadi pada try
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegistration;
    private javax.swing.JTextField txtCustomercode;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtRoom;
    // End of variables declaration//GEN-END:variables
}
